# Generated by Django 5.1.6 on 2025-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='content_images')),
            ],
        ),
    ]
